apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resimojavnozdravstvo
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: resimojavnozdravstvo
    newName: rg.fr-par.scw.cloud/djnd/resimojavnozdravstvo
    newTag: '01bf0da417b2aa2cfdb7da1490458f4a086b328c'
